import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import { verifySession } from "@/lib/auth";

export async function POST(request: NextRequest) {
  try {
    const session = await verifySession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const body = await request.json();
    const {
      promptHistory,
      skidlCode,
      kicadPcb,
      kicadSch,
      netlist,
      spice,
      cir,
      lib,
      schematicSvg,
      gerberZipBase64,
      drillZipBase64,
      stepBase64,
    } = body;

    if (!skidlCode) {
      return NextResponse.json(
        { error: "No SKiDL code to export" },
        { status: 400 }
      );
    }

    const zip = new JSZip();

    const sessionFolder = zip.folder("session");
    const compiledFolder = zip.folder("compiled");

    const prompts = Array.isArray(promptHistory)
      ? promptHistory.filter((item): item is string => typeof item === "string")
      : [];

    const metadata = {
      version: 1,
      exportedAt: new Date().toISOString(),
      hasCompiledOutput: Boolean(kicadPcb || kicadSch || netlist || spice || cir || lib || schematicSvg || gerberZipBase64 || drillZipBase64 || stepBase64),
      generatedFiles: [
        kicadPcb ? "circuit.kicad_pcb" : null,
        kicadSch ? "circuit.kicad_sch" : null,
        netlist ? "circuit.net" : null,
        spice ? "circuit.spice" : null,
        cir ? "circuit.cir" : null,
        lib ? "circuit.lib" : null,
        schematicSvg ? "circuit.svg" : null,
        gerberZipBase64 ? "gerbers.gbr.zip" : null,
        drillZipBase64 ? "drills.drl.zip" : null,
        stepBase64 ? "circuit.step" : null,
      ].filter(Boolean),
    };

    // Session payload
    sessionFolder?.file("chat_history.txt", prompts.join("\n\n"));
    sessionFolder?.file("skidl_code.py", skidlCode);
    sessionFolder?.file("metadata.json", JSON.stringify(metadata, null, 2));

    // Backward-compatible root files
    zip.file("circuit.py", skidlCode);
    zip.file("chat_history.txt", prompts.join("\n\n"));

    // Include KiCad files if available
    if (kicadPcb) {
      zip.file("circuit.kicad_pcb", kicadPcb);
      compiledFolder?.file("circuit.kicad_pcb", kicadPcb);
    }
    if (kicadSch) {
      zip.file("circuit.kicad_sch", kicadSch);
      compiledFolder?.file("circuit.kicad_sch", kicadSch);
    }
    if (netlist) {
      zip.file("circuit.net", netlist);
      compiledFolder?.file("circuit.net", netlist);
    }
    if (spice) {
      zip.file("circuit.spice", spice);
      compiledFolder?.file("circuit.spice", spice);
    }
    if (cir) {
      zip.file("circuit.cir", cir);
      compiledFolder?.file("circuit.cir", cir);
    }
    if (lib) {
      zip.file("circuit.lib", lib);
      compiledFolder?.file("circuit.lib", lib);
    }
    if (schematicSvg) {
      zip.file("circuit.svg", schematicSvg);
      compiledFolder?.file("circuit.svg", schematicSvg);
    }
    if (gerberZipBase64) {
      const gerberData = Buffer.from(gerberZipBase64, "base64");
      zip.file("gerbers.gbr.zip", gerberData);
      compiledFolder?.file("gerbers.gbr.zip", gerberData);
    }
    if (drillZipBase64) {
      const drillData = Buffer.from(drillZipBase64, "base64");
      zip.file("drills.drl.zip", drillData);
      compiledFolder?.file("drills.drl.zip", drillData);
    }
    if (stepBase64) {
      const stepData = Buffer.from(stepBase64, "base64");
      zip.file("circuit.step", stepData);
      compiledFolder?.file("circuit.step", stepData);
    }

    // Add a README
    zip.file(
      "README.md",
      `# AutoPCB Export

This archive was generated by AutoPCB.

## Files
- \`circuit.py\` — SKiDL Python source code
${prompts.length > 0 ? "- `chat_history.txt` — Prompt history from the session\n" : ""}${prompts.length > 0 ? "- `session/chat_history.txt` — Session chat history\n" : ""}- \`session/skidl_code.py\` — Session SKiDL code snapshot
${prompts.length > 0 ? "- `session/metadata.json` — Session metadata\n" : "- `session/metadata.json` — Session metadata\n"}${kicadPcb ? "- `circuit.kicad_pcb` — KiCad PCB layout file\n" : ""}${kicadPcb ? "- `compiled/circuit.kicad_pcb` — Compiled PCB output\n" : ""}${kicadSch ? "- `circuit.kicad_sch` — KiCad schematic file\n" : ""}${netlist ? "- `circuit.net` — Netlist file\n" : ""}${spice ? "- `circuit.spice` — SPICE netlist\n" : ""}${cir ? "- `circuit.cir` — SPICE circuit file\n" : ""}${lib ? "- `circuit.lib` — Library file\n" : ""}${schematicSvg ? "- `circuit.svg` — Browser-viewable schematic image\n" : ""}${gerberZipBase64 ? "- `gerbers.gbr.zip` — Gerber manufacturing files\n" : ""}${drillZipBase64 ? "- `drills.drl.zip` — Drill files\n" : ""}${stepBase64 ? "- `circuit.step` — 3D STEP model\n" : ""}

## Usage
1. Install SKiDL: \`pip install skidl\`
2. Run the circuit: \`python circuit.py\`
3. Open the generated files in KiCad
`
    );

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    return new NextResponse(Buffer.from(zipBuffer), {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": 'attachment; filename="autopcb-export.zip"',
      },
    });
  } catch (error: unknown) {
    const message =
      error instanceof Error ? error.message : "Unknown error occurred";
    console.error("[/api/export] Error:", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
