import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import { verifySession } from "@/lib/auth";

export async function POST(request: NextRequest) {
  try {
    const session = await verifySession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const body = await request.json();
    const { skidlCode, kicadPcb, kicadSch, netlist } = body;

    if (!skidlCode) {
      return NextResponse.json(
        { error: "No SKiDL code to export" },
        { status: 400 }
      );
    }

    const zip = new JSZip();

    // Always include the Python source
    zip.file("circuit.py", skidlCode);

    // Include KiCad files if available
    if (kicadPcb) {
      zip.file("circuit.kicad_pcb", kicadPcb);
    }
    if (kicadSch) {
      zip.file("circuit.kicad_sch", kicadSch);
    }
    if (netlist) {
      zip.file("circuit.net", netlist);
    }

    // Add a README
    zip.file(
      "README.md",
      `# AutoPCB Export

This archive was generated by AutoPCB.

## Files
- \`circuit.py\` — SKiDL Python source code
${kicadPcb ? "- `circuit.kicad_pcb` — KiCad PCB layout file\n" : ""}${
        kicadSch ? "- `circuit.kicad_sch` — KiCad schematic file\n" : ""
      }${netlist ? "- `circuit.net` — Netlist file\n" : ""}

## Usage
1. Install SKiDL: \`pip install skidl\`
2. Run the circuit: \`python circuit.py\`
3. Open the generated files in KiCad
`
    );

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    return new NextResponse(Buffer.from(zipBuffer), {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": 'attachment; filename="autopcb-export.zip"',
      },
    });
  } catch (error: unknown) {
    const message =
      error instanceof Error ? error.message : "Unknown error occurred";
    console.error("[/api/export] Error:", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
