import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import { verifySession } from "@/lib/auth";

export async function POST(request: NextRequest) {
  try {
    const session = await verifySession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const body = await request.json();
    const {
      skidlCode,
      kicadPcb,
      kicadSch,
      netlist,
      spice,
      cir,
      lib,
      schematicSvg,
      gerberZipBase64,
      drillZipBase64,
      stepBase64,
    } = body;

    if (!skidlCode) {
      return NextResponse.json(
        { error: "No SKiDL code to export" },
        { status: 400 }
      );
    }

    const zip = new JSZip();

    // Always include the Python source
    zip.file("circuit.py", skidlCode);

    // Include KiCad files if available
    if (kicadPcb) {
      zip.file("circuit.kicad_pcb", kicadPcb);
    }
    if (kicadSch) {
      zip.file("circuit.kicad_sch", kicadSch);
    }
    if (netlist) {
      zip.file("circuit.net", netlist);
    }
    if (spice) {
      zip.file("circuit.spice", spice);
    }
    if (cir) {
      zip.file("circuit.cir", cir);
    }
    if (lib) {
      zip.file("circuit.lib", lib);
    }
    if (schematicSvg) {
      zip.file("circuit.svg", schematicSvg);
    }
    if (gerberZipBase64) {
      zip.file("gerbers.gbr.zip", Buffer.from(gerberZipBase64, "base64"));
    }
    if (drillZipBase64) {
      zip.file("drills.drl.zip", Buffer.from(drillZipBase64, "base64"));
    }
    if (stepBase64) {
      zip.file("circuit.step", Buffer.from(stepBase64, "base64"));
    }

    // Add a README
    zip.file(
      "README.md",
      `# AutoPCB Export

This archive was generated by AutoPCB.

## Files
- \`circuit.py\` — SKiDL Python source code
${kicadPcb ? "- `circuit.kicad_pcb` — KiCad PCB layout file\n" : ""}${kicadSch ? "- `circuit.kicad_sch` — KiCad schematic file\n" : ""}${netlist ? "- `circuit.net` — Netlist file\n" : ""}${spice ? "- `circuit.spice` — SPICE netlist\n" : ""}${cir ? "- `circuit.cir` — SPICE circuit file\n" : ""}${lib ? "- `circuit.lib` — Library file\n" : ""}${schematicSvg ? "- `circuit.svg` — Browser-viewable schematic image\n" : ""}${gerberZipBase64 ? "- `gerbers.gbr.zip` — Gerber manufacturing files\n" : ""}${drillZipBase64 ? "- `drills.drl.zip` — Drill files\n" : ""}${stepBase64 ? "- `circuit.step` — 3D STEP model\n" : ""}

## Usage
1. Install SKiDL: \`pip install skidl\`
2. Run the circuit: \`python circuit.py\`
3. Open the generated files in KiCad
`
    );

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    return new NextResponse(Buffer.from(zipBuffer), {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": 'attachment; filename="autopcb-export.zip"',
      },
    });
  } catch (error: unknown) {
    const message =
      error instanceof Error ? error.message : "Unknown error occurred";
    console.error("[/api/export] Error:", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
